version: '3.8'

services:
  zurg-repair:
    image: ghcr.io/maulik9898/zurg-repair:latest
    container_name: zurg-repair-prod
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/config/config.yaml:ro
    environment:
      - NODE_ENV=production
      - SCHEDULER_MODE=true
      - LOG_LEVEL=info
      - TZ=UTC
      - ZURG_CONFIG_FILE=/config/config.yaml
    healthcheck:
      test: [ "CMD", "bun", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
